name: Docker

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: bass_bot
  EVENT: ${{ github.event_name }}

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build . --file Dockerfile --tag $IMAGE_NAME
          
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u kz159 --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=kz159/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION="latest"
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION